### ISSUE TITLE
privs

### ISSUE THREAD

**Issue by paulirish** [patrickhulce/git3po#25]
@patrickhulce  theres a bit of work needed to bring this repo up to date. (from travis to gha, maybe drop babel, a --version feature i needed)

i'd love if me and connor had push/maintain access here, but if not, i'm happy to fork. my guess is you're a bit busy now to help maintain/review stuff here, but if you think otherwise, then we can keep things as is. :)

**Comment by patrickhulce** [comment]
Looks like @connorjclark already had access, haha, invite sent @paulirish!
